### PR TITLE
spec file to build RPM packages

### PR DESCRIPTION
**Pull request by romanofski**
See purebred-mua/purebred#109 for more information.

### CODE REVIEW

**Comment by romanofski** [comment]
This one is pretty much autogenerated from `cabal-rpm` without any changes.

**Comment by frasertweedale** [comment]
@romanofski is this good to go?  I leave it to you to merge it - you are the packaging guru :)

**Comment by romanofski** [comment]
Yes good to go. But in light of recent activity I think I'll change the release attribute to use the got Sha and setup nightlies. I only realised it for purebred after I merged the spec.

**Comment by romanofski** [comment]
Found out it's trickier than I thought to get the SHA to setup nightlies. So I'll merge this and think of something later.

**Pull request merged**
